name: Сообщить о проблеме
description: Для проблем, которые не подходят под другие шаблоны.
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время сообщить о проблеме. Этот шаблон - для любых проблем, которые не подходят под другие шаблоны.
        За обратной связью и помощью обращайтесь в наш [Discord](https://wiki.lost-paradise.space/discord).
  - type: input
    attributes:
      label: В какой версии возникла проблема?
      description: Версию можно посмотреть в игре - откройте список изменений, она указана в правом нижнем углу окна.
      placeholder: lost-light/aa1337b
    validations:
      required: false
  - type: textarea
    attributes:
      label: Описание
      description: |
        Чёткое и краткое описание проблемы.
        Если проблема визуальная, приложите скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Как воспроизвести
      description: Перечислите шаги, чтобы воспроизвести проблему.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительная информация
      description: Любые другие подробности о проблеме.
    validations:
      required: false
