ignored_paths:
- "Resources/Locale/ru-RU/datasets"
- "Resources/Locale/ru-RU/_LP"
- "Resources/Locale/ru-RU/_corvax"
ignored_untranslated_paths:
# Названия клавиш, буквы каналов цвета, формулы газов
- "Resources/Locale/ru-RU/robust-toolbox/input.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/controls.ftl"
- "Resources/Locale/ru-RU/atmos/gases.ftl"
# Заклинания и тарабарщина магов, авторы артов лобби
- "Resources/Locale/ru-RU/magic/spells-actions.ftl"
- "Resources/Locale/ru-RU/teleportation/teleportation-menu-gui.ftl"
- "Resources/Locale/ru-RU/advertisements/vending/magivend.ftl"
- "Resources/Locale/ru-RU/lobby/lobby-state-background.ftl"
ignored_variable_mismatch_paths:
- "Resources/Locale/ru-RU/stack/stacks.ftl"
- "Resources/Locale/ru-RU/bed/cryostorage/cryogenic-storage.ftl"
- "Resources/Locale/ru-RU/game-ticking/game-ticker.ftl"
- "Resources/Locale/ru-RU/chat/managers/chat-manager.ftl"
# В русском притяжательное ("his tail") не нужно, $entity в части эмоций не используется
- "Resources/Locale/ru-RU/chat/emotes.ftl"
no_translate_tokens: # Вырезаются целыми словами, регистр не важен
# Название сервера
- "Lost Paradise"
# Корпорации и бренды
- "Nanotrasen"
- "Nanotrasen CRPX-229"
- "Discount Dan"
- "Getmore Chocolate Corp"
- "Mr. Chang"
- "Monkin' Donuts"
- "Donut Corp."
- "Robust Softdrinks"
- "Space-Up!"
- "Sun-kist"
- "Pwr Game"
- "Ue No"
- "LV426"
# Оружие и снаряжение
- "C-20r"
- "C-20r ROW"
- "C-4"
- "China-Lake"
- "L6 SAW"
- "L6C ROW"
- "N1984"
- "WT550"
- "LR-30"
- "PF20"
# Реагенты
- "left-4-zed"
- "Plant-B-Gone"
# Технические подписи и коды
- "2.1 REV 1"
- "7.2 REV 6"
- "$run power_net_query"
- "DEAD-BEEF"
- "NT-"
- "SYN-"
# Чат, админка, консоль
- "LOOC"
- "OOC"
- "ID"
- "IP"
- "HWID"
- "GUID"
- "EntityUid"
- "VIP"
- "UwU"
- "x"
- "Y"
# Сервисы
- "Discord"
- "GitHub"
- "Telegram"
- "Boosty"
# Аббревиатуры интерфейса, названия серверов и газов
- "VV"
- "TP"
- "NPC"
- "BZ"
- "STARLIGHT"
- "Wizden"
- "TRIESTEPORT"
- "setgamepreset"
- "1.0 REV 1"
- "RGB"

- "ZXA"
- "XP"
- "OwO"
- "GPP-"
- "AIR-"
- "GFL-"
- "GMR-"
- "GMM-"
- "ASP-"
- "TheAnaRina"
- "Conflee"
- "voy0099"
- "ItsAbby11"
- "Ramblinger"
- "ramblinger"
- "JustAdler"
- "Prazat911"
- "TheKillerDumb"
- "Bukkataro"
- "Zigo"
- "Darkrell"
- "Dispace"
- "IQlvlZero"
- "m0lem4n"
- "rickery"
- "swonki"
- "wintergem18"
- "deltaVelocity"
- "silkielol"
- "xxhotgirl69"
- "Tpto"
- "[color=#ff0004]"
- "LSE-400c"
- "LSE-1200c"
- "SEMI"
- "%E#R@R$#%$"
- "F"
- "L"
- "U"
- "R"
- "D"
- "B"
- "H₂"
- "He"
- "VRAM"
- "null"
- "UITest2"
- "Pipe"
- "Fents & Co Shuttleworks"
- "Interdyne Pharmaceutics"
- "Starkist"
- "NaN"
- "TSF-Baton-Model5"
- "m1911"
- "sp-8t"
- "sp-8ar"
- "TSF-Model17"
- "Aussec Armory M-52"
- "SP-91-RC"
- "WT550r"
- "WT550g"
- "Liber Chaotica"
- "Ultra AC-2"
- "Flipped, R&D"
- "CODE-9 ROW"
- "PS-3ETO"
- "PS Z46"
- "PS Z77 T1"
- "N1912"
