name: "Labels: Size"

# Cancel older jobs on PRs when new changes are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: pull_request_target

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
        with:
          # Custom size configuration
          sizes: >
            {
              "0": "Размер: XS",
              "10": "Размер: S",
              "100": "Размер: M",
              "1000": "Размер: L",
              "5000": "Размер: XL"
            }
