name: Check PR Target Branch

# Cancel older jobs on PRs when new changes are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-target-branch:
    if: github.actor != 'Lost-Paradise-Bot' && github.actor != 'starlightgithub[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR targets master
        env:
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          SOURCE_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "PR: $SOURCE_REPO:$SOURCE_BRANCH -> $TARGET_BRANCH"

          if [[ "$SOURCE_REPO" == "${{ github.repository }}" &&
                (("$SOURCE_BRANCH" == "master" && "$TARGET_BRANCH" == "stable") ||
                 ("$SOURCE_BRANCH" == "stable" && "$TARGET_BRANCH" == "master")) ]]; then
            echo "Разрешено: PR между master и stable"
            exit 0
          fi

          # Все остальные PR должны идти в master
          if [ "$TARGET_BRANCH" != "master" ]; then
            echo "::error::PR должен быть направлен в ветку 'master', а направлен в '$TARGET_BRANCH'. Смените целевую ветку на 'master'."
            exit 1
          else
            echo "Всё верно: PR направлен в 'master'"
          fi
